name: 02 - Workflow Events
on: 
    push: 
        branches: [develop]
    workflow_dispatch: 
    pull_request: 
        branches: [main]
    schedule:
        - cron: 30 10 30 01 04
    
jobs:
    echo-evt:
        runs-on: ubuntu-latest
        steps:
            - name: echo trigger
              run: |
                   date
                   echo "Event name: ${{github.event_name}}"
