name: 02 - Workflow Events
on: 
    push: 
    workflow_dispatch: 
    
jobs:
    echo-evt:
        runs-on: ubuntu-latest
        steps:
            - name: echo trigger
              run: |
                   echo "Event name: ${{github.event_name}}"