name: "05 - 2 - Event Filters and Activity"
on: 
    pull_request: 
        branches: main
        types: 
            closed
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "Running whenever a PR is closed."
    