name: "06 - Contexts"
on: 
    workflow_dispatch: 
    push: 
        branches: [main,develop]
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo github context"
              run: |
                   echo "Event name ${{github.event_name}}"
                   echo "Event name ${{github.ref}}"
                   echo "Event name ${{github.ref_name}}"
                   echo "Event name ${{github.sha}}"
                   echo "Event name ${{github.actor}}"
                   echo "Event name ${{github.workflow}}"
                   echo "Event name ${{github.run_id}}"
                   echo "Event name ${{github.run_number}}"
            - name: "Retrieve repository variable"
              run: | 
                   echo "My repo var is : ${{env.MY_VAR}}"


