name: "06 - Contexts"
on: 
    workflow_dispatch: 
    push: 
        branches: [main,develop]
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo github context"
              run: |
                   echo "Event name ${{github.event_name}}"
                   echo "Full Branch name ${{github.ref}}"
                   echo "Branch name ${{github.ref_name}}"
                   echo "Sha name ${{github.sha}}"
                   echo "Actor name ${{github.actor}}"
                   echo "Workflow name ${{github.workflow}}"
                   echo "Run id name ${{github.run_id}}"
                   echo "Run number  ${{github.run_number}}"
            - name: "Retrieve repository variable"
<<<<<<< HEAD
              run: |
=======
              run: | 
>>>>>>> 31eeabfe32cc407a7668c89b182f40a5a85ef084
                   echo "My repo var is : ${{env.MY_VAR}}"


